bridges = []
persistence_dir = ".holochain/holo"

[[agents]]
id = "hp-admin-agent"
keystore_file = "agent-1.key"
name = "HP Admin"
public_address = "HcScjkqc7F7A98nob966SAHbD7FFg67m7E8A3VxnGo3Vaptzrex936s7395hZwI"

[[dnas]]
file = "dna-src/dna/react-graphql/dist/react-graphql-template.dna.json"
hash = "QmSSJpZy4ctBr25rzVAhX7KXWhd1m55UPSZQ34AMb7Yvrz"
id = "react-graphql-dna"

[[instances]]
agent = "hp-admin-agent"
dna = "react-graphql-dna"
id = "react-graphql"

[instances.storage]
path = ".holochain/holo/storage/hp-admin-agent/react-graphql"
type = "file"

[[interfaces]]
id = "websocket-interface"

[interfaces.driver]
port = 3400
type = "websocket"

[[interfaces.instances]]
id = "react-graphql"

[[interfaces]]
admin = true
id = "http-interface"

[interfaces.driver]
port = 3300
type = "http"

[[interfaces.instances]]
id = "react-graphql"

[logger]
type = "debug"

[logger.rules]

[[logger.rules.rules]]
color = "red"
exclude = false
pattern = "^err/"

[[logger.rules.rules]]
color = "white"
exclude = false
pattern = "^debug/dna"

[network]
sim2h_url = "ws://public.sim2h.net:9000"
type = "sim2h"
